name: HBBEVCO
favicon: null
layout_spectrum: 0
typography_spectrum: 0.61625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b3b8bb'
    - '#d6dcdc'
    - '#000000'
    - '#666f74'
    - '#2e302f'
  brandStrength: 0
  lightness: 0.9304185411892831
  saturation: 0.4375
  rhythmicContrast: 0.9219226180575788
purpose: []
